import { useEffect, useState } from "react";
import { api, money } from "../lib/api";
import type { ApprovalTask } from "../types";
import { StatusBadge } from "../components/StatusBadge";

export function Approvals() {
  const [tasks,setTasks]=useState<ApprovalTask[]>([]); const [comments,setComments]=useState<Record<string,string>>({}); const [error,setError]=useState("");
  const load=()=>api<ApprovalTask[]>("/approvals/mine").then(setTasks).catch((e)=>setError(e.message));
  useEffect(()=>{void load();},[]);
  const decide=async(task:ApprovalTask,action:string)=>{try{await api(`/approvals/${task.id}/decision`,{method:"POST",body:JSON.stringify({action,comment:comments[task.id]||null})});setError("");load();}catch(e){setError((e as Error).message);}};
  const current = tasks.filter(t=>t.current);
  return <section><div className="section-heading"><div><p className="eyebrow">Moje práce</p><h1>Moje úkoly</h1><p className="muted">Každý úkol patří konkrétní revizi, rozúčtování, středisku a částce.</p></div></div>{error&&<div className="alert danger">{error}</div>}{!current.length?<div className="empty">Momentálně nemáte žádný aktivní úkol ke schválení.</div>:<div className="task-grid">{current.map(task=><article className="card approval-card" key={task.id}><div className="card-title"><div><h2>{task.invoice_number||"Faktura"}</h2><p>{task.supplier_name} · revize {task.revision}</p></div><StatusBadge value={task.assignment_status}/></div><div className="amount-block"><span>Faktura celkem<strong>{money(task.invoice_total,task.currency)}</strong></span><span>Schvaluji za {task.cost_center}<strong>{money(task.allocation_amount,task.currency)}</strong>{task.allocation_percentage!=null&&<small>{task.allocation_percentage} %</small>}</span></div>{task.allocation_note&&<p className="muted">Poznámka: {task.allocation_note}</p>}<dl className="metadata-grid"><div><dt>Datum vystavení</dt><dd>{String(task.invoice_data.issue_date||"—")}</dd></div><div><dt>Splatnost</dt><dd>{String(task.invoice_data.due_date||"—")}</dd></div><div><dt>Variabilní symbol</dt><dd>{String(task.invoice_data.variable_symbol||"—")}</dd></div><div><dt>Platební údaj</dt><dd>{String(task.invoice_data.iban||task.invoice_data.bank_account||"—")}</dd></div></dl><a className="button secondary" href={`/api/invoices/${task.invoice_id}/pdf`} target="_blank" rel="noreferrer">Zobrazit originální PDF</a><textarea placeholder="Komentář je povinný pro vrácení a zamítnutí" value={comments[task.id]||""} onChange={e=>setComments({...comments,[task.id]:e.target.value})}/><div className="decision-buttons"><button className="button primary" onClick={()=>void decide(task,"APPROVE")}>Schválit</button><button className="button warning" onClick={()=>void decide(task,"RETURN")}>Vrátit</button><button className="button danger" onClick={()=>void decide(task,"REJECT")}>Zamítnout</button></div></article>)}</div>}</section>;
}
